// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"github.com/decorickey/go-apps/internal/bmonster/infrastructure/sql"
)

// Injectors from wire.go:

func InitializeHandler() Handler {
	db := sql.NewDB()
	studioDAO := sql.NewStudioDao(db)
	performerDAO := sql.NewPerformerDao(db)
	timetableDAO := sql.NewTimetableDao(db)
	handlerHandler := NewHandler(studioDAO, performerDAO, timetableDAO)
	return handlerHandler
}
